### ISSUE TITLE
Help with quick start

### ISSUE THREAD

**Issue by ghost** [THARUNESHWAR-369/body-measurement-to-smpl-beta#1]
Hello! I'm currently very interested in the SMPL model family and would like to create a project based on it. I was looking for examples and came across your work. There's not much information online about body measurements -> SMPL... Could you briefly help me and explain how to connect your project with SMPL-X?

**Comment by tharuneshwar-s** [comment]
@IliiaKozhan its already in SMPL-X

check it out [server/lib/smplx.py](https://github.com/THARUNESHWAR-369/body-measurement-to-smpl-beta/blob/main/server/lib/smplx.py)
